version: 0.2

phases:
  install:
    commands:
      # Cache File unarchibe
      - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
      # yarn using
      - echo  packege install started
      - yarn --version
      - yarn install
      - echo Packege install completed
  build:
    commands:
      - echo Buil Start
      - yarn build
      - echo Build completed
  post_build:
    commands:
      - echo Archibe node module started
      - tar cf /tmp/node_modules.tar node_modules
      - echo Archibe node module completed
      - echo Clear CloudFrontCache started
      - aws cloudfront create-invalidation --ditribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: dist
cache:
    paths:
      - /tmp/node_modules.tar
